databases:
  - name: postgres
    databaseName: postgres_2bkk
    user: postgres_2bkk_user

services:
  - type: web
    name: Recipe App
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres_2bkk
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false